### PR TITLE
issue 9 possible resolution 

### PR DESCRIPTION
**Pull request by keyavi**
Please check the modifications if looks sensible than kindly merge.

### CODE REVIEW

**Comment by rob-p** [comment]
Hi @keyavi,

  These look good, except that rather than force the user to provide the aux directory, I'd read it in from the `cmd_info.json` file in the quant directory.  Both sailfish and salmon write out such a file.  If there is no entry for `auxDir`, it's safe to assume it takes the value `aux`.  Otherwise, the aux directory should be given then name it has according to the `cmd_info.json` file.  You can take a look at how I handle this in [wasabi](https://github.com/COMBINE-lab/wasabi) if my description here isn't clear.

**Comment by keyavi** [comment]
Hi Rob,

Yes you are right about putting aux conditionally depending on user's
choice.
Thats why I made eqfilesuffix flag as non necessary flag and provided aux
as the default path if not provided.
I avoided putting things into YAML since all the things in Yaml were all
necessary.
Hope it make sense.

--Avi

**Comment by rob-p** [comment]
@keyavi ,

  Right; I'm not suggesting putting it in the yaml, I'm suggesting reading it from the output of sailfish / salmon.  If the user specifies a non-standard (i.e. non-`aux`) parameter, then the path they provided to sailfish / salmon will be encoded in the `cmd_info.json` file in salmon's / sailfish's quantification directory.

**Comment by keyavi** [comment]
Please check #11

**Comment by rob-p** [comment]
This is superseded by PR#11.

**Pull request closed without merging**
